Repository adobe/aepsdk-edgebridge-ios, pull requests merged in 2024-03, with the labels that each got.

#60 Update to support v5 data format
  Podfile.lock
  Sources/EdgeBridge.swift
  Sources/EdgeBridgeConstants.swift
  TestApps/TestAppSwiftUI/ContentView.swift
  Tests/FunctionalTests/EdgeBridgeFunctionalTests.swift
  Tests/UnitTests/EdgeBridgeTests.swift
Labels: feature

#68 update circleci + workflows for v5.0.0
  .circleci/config.yml
  .github/workflows/release.yml
Labels: tooling

#83 [doc] Update data-format.md linkType to "other"
  Documentation/data-format.md
Labels: documentation
